security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    admin: { password: something, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            form_login:
                #login_path: /login
                check_path: /login_check
                provider: fos_userbundle
                login_path: index
                use_forward:    false
                failure_path:   null
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: index
            anonymous: ~

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }